name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@github-action-test-1
    - name: Install tools
      run: echo Install tools!
    - name: Setup repos
      run: |
        echo Setup repos,
        ./cibuild.sh -s
